name: ci
run-name: ${{ github.actor }} triggered CI
on: [push]
jobs:
  test-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install --user -e .
      - run: pytest tests
